// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleDeleteRequest) Reset() {
	*x = SingleDeleteRequest{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleDeleteRequest) ProtoMessage() {}

func (x *SingleDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleDeleteRequest.ProtoReflect.Descriptor instead.
func (*SingleDeleteRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *SingleDeleteRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SingleInsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleInsertRequest) Reset() {
	*x = SingleInsertRequest{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleInsertRequest) ProtoMessage() {}

func (x *SingleInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleInsertRequest.ProtoReflect.Descriptor instead.
func (*SingleInsertRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *SingleInsertRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

type BatchInsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertRequest) Reset() {
	*x = BatchInsertRequest{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertRequest) ProtoMessage() {}

func (x *BatchInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertRequest.ProtoReflect.Descriptor instead.
func (*BatchInsertRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *BatchInsertRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CheckIfExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIfExistsRequest) Reset() {
	*x = CheckIfExistsRequest{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfExistsRequest) ProtoMessage() {}

func (x *CheckIfExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckIfExistsRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *CheckIfExistsRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CheckIfExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIfExistsResponse) Reset() {
	*x = CheckIfExistsResponse{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfExistsResponse) ProtoMessage() {}

func (x *CheckIfExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckIfExistsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *CheckIfExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x06server\"+\n" +
	"\x13SingleDeleteRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"+\n" +
	"\x13SingleInsertRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\a\n" +
	"\x05Empty\",\n" +
	"\x12BatchInsertRequest\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\",\n" +
	"\x14CheckIfExistsRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"/\n" +
	"\x15CheckIfExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xff\x01\n" +
	"\tDbService\x124\n" +
	"\x06Insert\x12\x1b.server.SingleInsertRequest\x1a\r.server.Empty\x128\n" +
	"\vBatchInsert\x12\x1a.server.BatchInsertRequest\x1a\r.server.Empty\x12L\n" +
	"\rCheckIfExists\x12\x1c.server.CheckIfExistsRequest\x1a\x1d.server.CheckIfExistsResponse\x124\n" +
	"\x06Delete\x12\x1b.server.SingleDeleteRequest\x1a\r.server.EmptyB\x06Z\x04./pbb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_proto_goTypes = []any{
	(*SingleDeleteRequest)(nil),   // 0: server.SingleDeleteRequest
	(*SingleInsertRequest)(nil),   // 1: server.SingleInsertRequest
	(*Empty)(nil),                 // 2: server.Empty
	(*BatchInsertRequest)(nil),    // 3: server.BatchInsertRequest
	(*CheckIfExistsRequest)(nil),  // 4: server.CheckIfExistsRequest
	(*CheckIfExistsResponse)(nil), // 5: server.CheckIfExistsResponse
}
var file_server_proto_depIdxs = []int32{
	1, // 0: server.DbService.Insert:input_type -> server.SingleInsertRequest
	3, // 1: server.DbService.BatchInsert:input_type -> server.BatchInsertRequest
	4, // 2: server.DbService.CheckIfExists:input_type -> server.CheckIfExistsRequest
	0, // 3: server.DbService.Delete:input_type -> server.SingleDeleteRequest
	2, // 4: server.DbService.Insert:output_type -> server.Empty
	2, // 5: server.DbService.BatchInsert:output_type -> server.Empty
	5, // 6: server.DbService.CheckIfExists:output_type -> server.CheckIfExistsResponse
	2, // 7: server.DbService.Delete:output_type -> server.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
